spring:
  datasource:
    url: jdbc:postgresql://localhost:50002/apclinic-dbname?autoReconnect=true
    username: apclinic-dbuser
    password: apclinic-dbpasswd
    driver-class-name: org.postgresql.Driver
    hikari.pool-name: apclinic-pool
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      use-new-id-generator-mappings: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp.use_jdbc_metadata_defaults: false
security:
  oauth2:
    client:
      accessTokenUri: http://localhost:30000/ap-sso/oauth/token
      clientId: com.gitlab.andrepenteado.apclinic
      clientSecret: apclinic-secret
      userAuthorizationUri: http://localhost:30000/ap-sso/oauth/authorize
    resource:
      userInfoUri: http://localhost:30000/ap-sso/user
server:
  port: 30002
  servlet:
    context-path: /ap-clinic