version: "3.7"
services:
  apclinic-dbserver:
    image: postgres:14-alpine
    container_name: apclinic-dbserver-container
    environment:
      POSTGRES_USER: apclinic-dbuser
      POSTGRES_PASSWORD: apclinic-dbpasswd
      POSTGRES_DB: apclinic-dbname
    volumes:
      - apclinic-pgdata:/var/lib/postgresql/data
    ports:
      - "50002:5432"
  apclinic-webapp:
    image: tomcat:9-jre17
    container_name: apclinic-webapp-container
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    ports:
      - "30002:8080"
      - "28002:8001"
      - "21097:1099"
    entrypoint:
      - "catalina.sh"
      - "jpda"
      - "run"
    volumes:
      - ../../../target/ap-clinic.war:/usr/local/tomcat/webapps/ap-clinic.war
volumes:
  apclinic-pgdata:
