version: "3.7"
services:
  apclinic-dbserver:
    image: postgres:11-alpine
    container_name: apclinic-dbserver-container
    environment:
      POSTGRES_USER: apclinic-dbuser
      POSTGRES_PASSWORD: apclinic-dbpasswd
      POSTGRES_DB: apclinic-dbname
    volumes:
      - apclinic-pgdata:/var/lib/postgresql/data
    ports:
      - "50002:5432"
  apclinic-webapp:
    image: registry.gitlab.com/andrepenteado/ap-clinic
    container_name: apclinic-webapp-container
    ports:
      - "30002:8080"
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
volumes:
  apclinic-pgdata: